pull_request_rules:
  - name: test with comment and label
    conditions:
      - base == main
    actions:
      label:
        add:
          - security-test
      comment:
        message: "Mergify hat diesen PR erfolgreich verarbeitet!"
