pull_request_rules:
  - name: labeling rule
    conditions:
      - base == main
    actions:
      label:
        add:
          - security-test
      comment:
        message: "Mergify hat diesen Pull Request erkannt."
